# Generated by Django 2.2 on 2021-01-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_poll_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
