# Generated by Django 2.2 on 2021-01-24 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_poll_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='votes',
        ),
        migrations.AddField(
            model_name='poll',
            name='option1votes',
            field=models.ManyToManyField(related_name='option1votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='option2votes',
            field=models.ManyToManyField(related_name='option2votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
