# Generated by Django 2.2 on 2021-01-24 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_remove_poll_option1votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option1votes',
            field=models.ManyToManyField(related_name='option1votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
