# Generated by Django 2.2 on 2021-01-24 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_poll_option1votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option1votes',
            field=models.ManyToManyField(related_name='_poll_option1votes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option2votes',
            field=models.ManyToManyField(related_name='_poll_option2votes_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
