# Generated by Django 2.2 on 2021-01-24 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210123_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option1votes',
            field=models.ManyToManyField(related_name='option1votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option2votes',
            field=models.ManyToManyField(related_name='option2votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
