# Generated by Django 2.2 on 2021-01-30 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20210124_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option1votes',
            field=models.ManyToManyField(blank=True, related_name='option1votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option2votes',
            field=models.ManyToManyField(blank=True, related_name='option2votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
